language: android
android:
  components:
    - build-tools-28.0.3
    - android-21
    - extra-android-m2repository
    - extra-android-support
before_script:
  - chmod +x gradlew    
script:
  - ./gradlew assembleRelease

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
