//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoTimeFix.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoTimeFix.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: .
        /// </summary>
        public static string About_Author {
            get {
                return ResourceManager.GetString("About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryolitia.
        /// </summary>
        public static string About_Neuron {
            get {
                return ResourceManager.GetString("About_Neuron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source License.
        /// </summary>
        public static string About_OpenSourceLicense {
            get {
                return ResourceManager.GetString("About_OpenSourceLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github repo: .
        /// </summary>
        public static string About_OpenSourceLink {
            get {
                return ResourceManager.GetString("About_OpenSourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram: .
        /// </summary>
        public static string About_Telegram {
            get {
                return ResourceManager.GetString("About_Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to all open source software contributors for going forward.
        /// </summary>
        public static string About_ThanksToOpenSource {
            get {
                return ResourceManager.GetString("About_ThanksToOpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Time Fix.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string CodeEditWindow_Compile {
            get {
                return ResourceManager.GetString("CodeEditWindow_Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiled successfully.
        /// </summary>
        public static string CodeEditWindow_CompileSuccess {
            get {
                return ResourceManager.GetString("CodeEditWindow_CompileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current creation time: .
        /// </summary>
        public static string MainWindow_CurrentCreationTime {
            get {
                return ResourceManager.GetString("MainWindow_CurrentCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current last write time: .
        /// </summary>
        public static string MainWindow_CurrentModificationTime {
            get {
                return ResourceManager.GetString("MainWindow_CurrentModificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user: .
        /// </summary>
        public static string MainWindow_CurrentUser {
            get {
                return ResourceManager.GetString("MainWindow_CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user group: .
        /// </summary>
        public static string MainWindow_CurrentUserGroup {
            get {
                return ResourceManager.GetString("MainWindow_CurrentUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom file processing class.
        /// </summary>
        public static string MainWindow_CustomFileProcessingClass {
            get {
                return ResourceManager.GetString("MainWindow_CustomFileProcessingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or folder path.
        /// </summary>
        public static string MainWindow_FolderFilePath {
            get {
                return ResourceManager.GetString("MainWindow_FolderFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Time: .
        /// </summary>
        public static string MainWIndow_NewTime {
            get {
                return ResourceManager.GetString("MainWIndow_NewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run As Admin.
        /// </summary>
        public static string MainWindow_RunAsAdmin {
            get {
                return ResourceManager.GetString("MainWindow_RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run As Trust Installer.
        /// </summary>
        public static string MainWindow_RunAsTrustInstaller {
            get {
                return ResourceManager.GetString("MainWindow_RunAsTrustInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string MainWindow_Start {
            get {
                return ResourceManager.GetString("MainWindow_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string ProcessWindow_Detail {
            get {
                return ResourceManager.GetString("ProcessWindow_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ProcessWindow_File {
            get {
                return ResourceManager.GetString("ProcessWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Time.
        /// </summary>
        public static string ProcessWindow_NewTime {
            get {
                return ResourceManager.GetString("ProcessWindow_NewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ProcessWindow_Status {
            get {
                return ResourceManager.GetString("ProcessWindow_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path should not be empty.
        /// </summary>
        public static string Rule_PathNonNull {
            get {
                return ResourceManager.GetString("Rule_PathNonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not exist.
        /// </summary>
        public static string Rule_PathNotExist {
            get {
                return ResourceManager.GetString("Rule_PathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process only media files.
        /// </summary>
        public static string Setting_MediaOnly {
            get {
                return ResourceManager.GetString("Setting_MediaOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only process files with MIME type &quot;image/*&quot; or &quot;video/*&quot; when batch processing.
        /// </summary>
        public static string Setting_MediaOnlySummary {
            get {
                return ResourceManager.GetString("Setting_MediaOnlySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open media.
        /// </summary>
        public static string Setting_OpenMedia {
            get {
                return ResourceManager.GetString("Setting_OpenMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer EXIF.
        /// </summary>
        public static string Setting_PreferExif {
            get {
                return ResourceManager.GetString("Setting_PreferExif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to read EXIF tag firstly.
        /// </summary>
        public static string Setting_PreferExifSummary {
            get {
                return ResourceManager.GetString("Setting_PreferExifSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe mode.
        /// </summary>
        public static string Setting_SafeMode {
            get {
                return ResourceManager.GetString("Setting_SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent time from being set before 1970 or after the current time.
        /// </summary>
        public static string Setting_SafeModeSummary {
            get {
                return ResourceManager.GetString("Setting_SafeModeSummary", resourceCulture);
            }
        }
    }
}
