//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoTimeFix.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoTimeFix.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Author:  的本地化字符串。
        /// </summary>
        public static string About_Author {
            get {
                return ResourceManager.GetString("About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cryolitia 的本地化字符串。
        /// </summary>
        public static string About_Neuron {
            get {
                return ResourceManager.GetString("About_Neuron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Source License 的本地化字符串。
        /// </summary>
        public static string About_OpenSourceLicense {
            get {
                return ResourceManager.GetString("About_OpenSourceLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github repo:  的本地化字符串。
        /// </summary>
        public static string About_OpenSourceLink {
            get {
                return ResourceManager.GetString("About_OpenSourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Telegram:  的本地化字符串。
        /// </summary>
        public static string About_Telegram {
            get {
                return ResourceManager.GetString("About_Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks to all open source software contributors for going forward 的本地化字符串。
        /// </summary>
        public static string About_ThanksToOpenSource {
            get {
                return ResourceManager.GetString("About_ThanksToOpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photo Time Fix 的本地化字符串。
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compile 的本地化字符串。
        /// </summary>
        public static string CodeEditWindow_Compile {
            get {
                return ResourceManager.GetString("CodeEditWindow_Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compiled successfully 的本地化字符串。
        /// </summary>
        public static string CodeEditWindow_CompileSuccess {
            get {
                return ResourceManager.GetString("CodeEditWindow_CompileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current creation time:  的本地化字符串。
        /// </summary>
        public static string MainWindow_CurrentCreationTime {
            get {
                return ResourceManager.GetString("MainWindow_CurrentCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current last write time:  的本地化字符串。
        /// </summary>
        public static string MainWindow_CurrentModificationTime {
            get {
                return ResourceManager.GetString("MainWindow_CurrentModificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current user:  的本地化字符串。
        /// </summary>
        public static string MainWindow_CurrentUser {
            get {
                return ResourceManager.GetString("MainWindow_CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current user group:  的本地化字符串。
        /// </summary>
        public static string MainWindow_CurrentUserGroup {
            get {
                return ResourceManager.GetString("MainWindow_CurrentUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom file processing class 的本地化字符串。
        /// </summary>
        public static string MainWindow_CustomFileProcessingClass {
            get {
                return ResourceManager.GetString("MainWindow_CustomFileProcessingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File or folder path 的本地化字符串。
        /// </summary>
        public static string MainWindow_FolderFilePath {
            get {
                return ResourceManager.GetString("MainWindow_FolderFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Time:  的本地化字符串。
        /// </summary>
        public static string MainWIndow_NewTime {
            get {
                return ResourceManager.GetString("MainWIndow_NewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run As Admin 的本地化字符串。
        /// </summary>
        public static string MainWindow_RunAsAdmin {
            get {
                return ResourceManager.GetString("MainWindow_RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run As Trust Installer 的本地化字符串。
        /// </summary>
        public static string MainWindow_RunAsTrustInstaller {
            get {
                return ResourceManager.GetString("MainWindow_RunAsTrustInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string MainWindow_Start {
            get {
                return ResourceManager.GetString("MainWindow_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string ProcessWindow_Copy {
            get {
                return ResourceManager.GetString("ProcessWindow_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        public static string ProcessWindow_Detail {
            get {
                return ResourceManager.GetString("ProcessWindow_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string ProcessWindow_File {
            get {
                return ResourceManager.GetString("ProcessWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Time 的本地化字符串。
        /// </summary>
        public static string ProcessWindow_NewTime {
            get {
                return ResourceManager.GetString("ProcessWindow_NewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string ProcessWindow_Status {
            get {
                return ResourceManager.GetString("ProcessWindow_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path should not be empty 的本地化字符串。
        /// </summary>
        public static string Rule_PathNonNull {
            get {
                return ResourceManager.GetString("Rule_PathNonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path not exist 的本地化字符串。
        /// </summary>
        public static string Rule_PathNotExist {
            get {
                return ResourceManager.GetString("Rule_PathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process only media files 的本地化字符串。
        /// </summary>
        public static string Setting_MediaOnly {
            get {
                return ResourceManager.GetString("Setting_MediaOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only process files with MIME type &quot;image/*&quot; or &quot;video/*&quot; when batch processing 的本地化字符串。
        /// </summary>
        public static string Setting_MediaOnlySummary {
            get {
                return ResourceManager.GetString("Setting_MediaOnlySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open media 的本地化字符串。
        /// </summary>
        public static string Setting_OpenMedia {
            get {
                return ResourceManager.GetString("Setting_OpenMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prefer EXIF 的本地化字符串。
        /// </summary>
        public static string Setting_PreferExif {
            get {
                return ResourceManager.GetString("Setting_PreferExif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to read EXIF tag firstly 的本地化字符串。
        /// </summary>
        public static string Setting_PreferExifSummary {
            get {
                return ResourceManager.GetString("Setting_PreferExifSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Safe mode 的本地化字符串。
        /// </summary>
        public static string Setting_SafeMode {
            get {
                return ResourceManager.GetString("Setting_SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevent time from being set before 1970 or after the current time 的本地化字符串。
        /// </summary>
        public static string Setting_SafeModeSummary {
            get {
                return ResourceManager.GetString("Setting_SafeModeSummary", resourceCulture);
            }
        }
    }
}
